# Generated by Django 5.2.5 on 2025-08-23 21:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UltimaAtualizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=6, unique=True)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Em Manutenção', 'Em Manutenção'), ('Indisponível', 'Indisponível')], default='Disponível', max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos', models.TextField()),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('data_previsao_saida', models.DateField(blank=True, null=True)),
                ('numero_os', models.CharField(max_length=50, verbose_name='Número da OS/Ticket')),
                ('status_os', models.CharField(choices=[('Aguardando Orçamento', 'Aguardando Orçamento'), ('Aguardando Nível 0', 'Aguardando Nível 0'), ('Aguardando Nível 1', 'Aguardando Nível 1'), ('Aguardando Nível 2', 'Aguardando Nível 2'), ('Aguardando Nível 3', 'Aguardando Nível 3')], max_length=50, verbose_name='Status da OS')),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manutencao', to='frota.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Indisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('veiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indisponibilidade', to='frota.veiculo')),
            ],
        ),
    ]
