# Generated by Django 5.2.5 on 2025-08-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_modeloveiculo_alter_veiculo_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencao',
            name='nome_oficina',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome da Oficina'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='status_os',
            field=models.CharField(choices=[('Aguardando Orçamento', 'Aguardando Orçamento'), ('Aguardando Nível 0', 'Aguardando Nível 0'), ('Aguardando Nível 1', 'Aguardando Nível 1'), ('Aguardando Nível 2', 'Aguardando Nível 2'), ('Aguardando Nível 3', 'Aguardando Nível 3'), ('Aprovado', 'Aprovado')], max_length=50, verbose_name='Status da OS'),
        ),
    ]
