# Generated by Django 5.2.5 on 2025-08-25 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_manutencao_nome_oficina_alter_manutencao_status_os'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='manutencao',
            name='cidade_oficina',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade da Oficina'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='regional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.regional'),
        ),
    ]
