# Generated by Django 5.2.5 on 2025-08-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_regional_manutencao_cidade_oficina_veiculo_regional'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='segmento',
            field=models.CharField(choices=[('LT', 'Linha de Transmissão'), ('SE', 'Subestação'), ('N/A', 'Não Aplicável')], default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='tipo_veiculo',
            field=models.CharField(choices=[('LEVE', 'Leve'), ('MEDIO', 'Médio'), ('PESADO', 'Pesado'), ('EQUIPAMENTO', 'Equipamento')], default='LEVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='regional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='frota.regional'),
            preserve_default=False,
        ),
    ]
