# Generated by Django 5.2.5 on 2025-11-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_veiculo_segmento_veiculo_tipo_veiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='status_os',
            field=models.CharField(choices=[('Aguardando Orçamento', 'Aguardando Orçamento'), ('Aguardando Orçamento', 'Aguardando Orçamento'), ('Aguardando Nível 1', 'Aguardando Nível 1'), ('Aguardando Nível 2', 'Aguardando Nível 2'), ('Aguardando Nível 3', 'Aguardando Nível 3'), ('Aprovado', 'Aprovado'), ('Garantia', 'Garantia'), ('N/A', 'N/A')], max_length=50, verbose_name='Status da OS'),
        ),
    ]
