# Generated by Django 5.2.5 on 2025-11-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0006_alter_manutencao_status_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='status_os',
            field=models.CharField(choices=[('Aguardando Orçamento', 'Aguardando Orçamento'), ('Aguardando Aprovação', 'Aguardando Aprovação'), ('Aprovado', 'Aprovado'), ('Garantia', 'Garantia'), ('N/A', 'N/A')], max_length=50, verbose_name='Status da OS'),
        ),
    ]
