# Generated by Django 5.2.5 on 2025-11-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0007_alter_manutencao_status_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='numero_os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da OS/Ticket'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='prefixo',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
